# Generated by Django 4.2.7 on 2023-11-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_book_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
